spring:
  datasource:
#   数据源基本配置
    username: root
    password: root
    url: jdbc:mysql://192.168.31.247:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 自定义数据源【DataSourceConfiguration数据源种类】
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    # spring boot自动初始化脚本，always每次都初始化，EMBEDDED只初始化内存数据库 NEVER不初始化
    initialization-mode: always
    schema:
      - classpath:department.sql
